export const BASE_API_URL = "https://localhost:7226/"
export const BASE_MOVIE_SERVICE = "api/movies"
export const BASE_ARTICLE_SERVICE = "api/articles"
export const BASE_LOCATION_SERVICE = "api/location"
export const BASE_ACCOUNT_SERVICE = "api/accounts"